stopTitles: "stopTitles.txt"
stopDescriptions: "stopDescriptions.txt"
stopLocations: "stopLocations.txt"
stopEmployees: "stopEmployees.txt"

linkedin:
  startPage: "https://www.linkedin.com/jobs/search/"
  listPage: "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search/"
  loginPage: "https://www.linkedin.com/login"
  jobSearchPage: "https://www.linkedin.com/jobs/search"
  default:
    location: "Germany"
    keywords: "java,developer"
    postedSecAgo: 86400
    remote: false
    lang: "EN"
  credentials:
    username: "lenhelncode@gmail.com"
    password: "l1e2n3a4"
#    убрать все в переменные

#spring:
#  config:
#    import: sm://
#  cloud:
#    gcp:
#      secretmanager:
#        enabled: true
#  cloud:
#    gcp:
#      project-id: just-plate-393810
#      secretmanager:
#        enabled: true
#        project-id: just-plate-393810

mail:
  smtp:
    auth: true
    host: smtp.gmail.com
    port: 587
    starttls:
      enable: true
  from: "job-seeking-app@gmail.com"
  to: "hostelsdirector@gmail.com"
  title: "New jobs"

variables:
  email:
#    username: ${sm://projects/just-plate-393810/secrets/EMAIL_USERNAME}
#    password: ${sm://projects/just-plate-393810/secrets/EMAIL_PASSWORD}
    username: "hostelsdirector@gmail.com"
    password: "cqlikzviegxzpzvz"


server:
  port : 8081